Vagrant.configure("2") do |config|
  # Конфигурация для первой виртуальной машины
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "debian/bullseye64" # Замените на имя образа, который вы хотите использовать
    vm1.vm.network "public_network",bridge: "Intel(R) Wi-Fi 6 AX200 160MHz"
    vm1.vm.provider "virtualbox" do |vb1|
      vb1.name = 'NEXERA1'
	  vb1.memory = 1024 # Выделить памяти (в мегабайтах)
      vb1.cpus = 1 # Выделить процессорных ядер
    end
  end

  # Конфигурация для второй виртуальной машины
  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "debian/bullseye64" # Замените на имя образа, который вы хотите использовать
    vm2.vm.network "public_network", bridge: "Intel(R) Wi-Fi 6 AX200 160MHz"
	vm2.vm.provider "virtualbox" do |vb2|
      vb2.name = 'NEXERA2_SEBE'
	  vb2.memory = 1024 # Выделить памяти (в мегабайтах)
      vb2.cpus = 1 # Выделить процессорных ядер
    end
  end

  # Конфигурация для третьей виртуальной машины
  config.vm.define "vm3" do |vm3|
    vm3.vm.box = "debian/bullseye64" # Замените на имя образа, который вы хотите использовать
    vm3.vm.network "public_network", bridge: "Intel(R) Wi-Fi 6 AX200 160MHz"
	vm3.vm.provider "virtualbox" do |vb3|
      vb3.memory = 1024 # Выделить памяти (в мегабайтах)
      vb3.cpus = 1 # Выделить процессорных ядер
	  vb3.name = 'NEXERA_SEBE'
    end
  end
end
