---
- name: "NGINX"
  hosts: yc
  become: yes
  remote_user: test
  tasks:
    - name: "update cache apt"
      ansible.builtin.apt:
        update-cache: true
        name: nginx
        state: present
      #when: ansible_os_family == "Debian"
    - name: "enable nginx service"
      ansible.builtin.systemd:
        name: nginx
        enabled: true
        state: started
    - name: "check url"
      ansible.builtin.uri:
        url: "http://localhost"
        return_content: true
      register: response
      failed_when: response.status != 200
    - name: debug
      ansible.builtin.debug:
        var: response.status
