---
- name: Install Clickhouse
  gather_facts: no
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
#      become: true
      remote_user: root
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - name: Clickhouse
      block:
        - name: Get clickhouse distribute
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/deb/pool/main/c/{{ item }}/{{ item }}_{{ clickhouse_version }}_amd64.deb"
            dest: "/tmp/{{ item }}_{{ clickhouse_version }}_amd64.deb"
            mode: '777'
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distribute
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/deb/pool/main/c/clickhouse-common-static/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
            dest: "/tmp/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
            mode: '644'
    - name: Install clickhouse packages
#      become: true
      remote_user: root
      ansible.builtin.apt:
        deb: "{{ item }}"
      with_items:
          - /tmp/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb
          - /tmp/clickhouse-client_{{ clickhouse_version }}_amd64.deb
          - /tmp/clickhouse-server_{{ clickhouse_version }}_amd64.deb
      notify: Start clickhouse service
    - name: Flush handlers
      meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client  --password='1234567' -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0

- name: Install vector
  hosts: clickhouse
  gather_facts: no
  remote_user: root
  handlers:
    - name: Start vector service
      remote_user: root
#      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
  tasks:
    - name: Vector
      block:
        - name: Get Vector distribute
          ansible.builtin.get_url:
            url: "https://apt.vector.dev/pool/v/ve/vector_0.41.1-1_amd64.deb"
            dest: "/tmp/vector.deb"
            mode: '644'
        - name: install Vector
#          become: true
          remote_user: root
          ansible.builtin.apt:
            deb: /tmp/vector.deb
          notify: Start vector service
        - name: Vector config
          become: true
          ansible.builtin.template:
            src: templates/vector.j2
            dest: /etc/vector/vector.yaml
            group: vector
            mode: '644'
          tags: config_vector         
          notify: Start vector service
        - name: Flush handlers
          ansible.builtin.meta: flush_handlers
            