services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./data:/etc/prometheus/
    ports:
      - "9090:9090"
    restart: always
    depends_on:
      - node-exporter

  node-exporter: #https://github.com/prometheus/node_exporter
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment: #https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#override-configuration-with-environment-variables
      - GF_SECURITY_ADMIN_USER=snake
      - GF_SECURITY_ADMIN_PASSWORD=snake
    volumes:
      - './grafana/provisioning:/etc/grafana/provisioning'
    restart: always
    depends_on:
      - prometheus