---
- name: "install zabbix aggent"
  hosts: cloud
  become: yes
  tasks:
    - name: " download zabbix repo "
      ansible.builtin.get_url:
         url: https://repo.zabbix.com/zabbix/6.4/debian/pool/main/z/zabbix-release/zabbix-release_6.4-1+debian11_all.deb
         dest: /tmp/zabbix-release_6.4-1+debian11_all.deb
      when: ansible_os_family == "Debian"
          
    - name: " install repo "
      ansible.builtin.apt:
        deb: /tmp/zabbix-release_6.4-1+debian11_all.deb   
           
    - name: " update cache and install zabbix agent "
      ansible.builtin.apt:
        update_cache: yes
        pkg:
          - zabbix-agent2
          - zabbix-agent2-plugin-*

    - name: " conf zabbix agent "
      ansible.builtin.replace:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: '^Server=127.0.0.1'
        replace: 'Server=158.160.14.0'
      notify:
        - restart zabbix_agent     
    
    - name: " update cache and install zabbix agent "
      ansible.builtin.systemd:
        name: zabbix-agent2
        state: started
        enabled: true              
  
  handlers:
    - name: restart zabbix_agent
      ansible.builtin.systemd:
        name: zabbix-agent2
        state: restarted

