apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-4
  labels: 
    app: "deploy-nginx"
    hw: "4"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-4
  template:
    metadata:
      labels:
        app: nginx-4
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - name: nginx-port
          containerPort: 80
      - name: network-multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8088"
        ports:
        - containerPort: 8080
          name: multitool

