apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
   app: nginx-4
  ports:
    - name: nginx-port
      port: 9001
      targetPort: nginx-port
    - name: multitool
      port: 9002
      targetPort: multitool
