version: "3"
services:
netology-db:
    image: postgres:latest # Образ, который мы будем использовать
    container_name: netology-db # Имя, которым будет называться наш контейнер
    ports: # Порты, которые мы пробрасываем с нашего докер сервера внутрь контейнера
    - 5432:5432
    volumes: # Папка, которую мы пробросим с докер сервера внутрь контейнера
    - /opt/postgres/pg_data:/var/lib/postgresql/data/pgdata
    environment: # Переменные среды
      POSTGRES_PASSWORD: 123 # Задаём пароль от пользователя postgres
      POSTGRES_DB: netology_db # БД которая сразу же будет создана
      PGDATA: /var/lib/postgresql/data/pgdata # Путь внутри контейнера, где будет папка pgdata
    networks:
      netology-lesson:
        ipv4_address: 172.19.0.2
        aliases:
        - netology-db
    restart: always # Режим перезапуска контейнера. Контейнер всегда будет перезапускаться
  pgadmin:
    image: dpage/pgadmin4:latest # Образ, который мы будем использовать
    container_name: netology-pgadmin # Имя, которым будет называться наш контейнер
    ports: # Порты, которые мы пробрасываем с нашего докер сервера внутрь контейнера
    - 8080:80
    environment: # Переменные среды
      PGADMIN_DEFAULT_EMAIL: netology@myemail.me
      PGADMIN_DEFAULT_PASSWORD: 123 # Задаём пароль от пользователя postgres
    networks:
      netology-lesson:
        ipv4_address: 172.19.0.3
        aliases:
        - netology-pgadmin
    restart: always # Режим перезапуска контейнера. Контейнер всегда будет перезапускаться
  zabbix-server:
    image: zabbix/zabbix-server-pgsql
    links:
    - netology-db
    container_name: netology-zabbix
    environment:
      DB_SERVER_HOST: '172.19.0.2'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
    - "10051:10051"
    networks:
      netology-lesson:
        ipv4_address: 172.19.0.4
    restart: always
  zabbix_wgui:
    image: zabbix/zabbix-web-apache-pgsql
    links:
    - netology-db
    - zabbix-server
    container_name: netology_zabbix_wgui
    environment:
      DB_SERVER_HOST: '172.19.0.2'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 123
      ZBX_SERVER_HOST: "zabbix_wgui"
      PHP_TZ: "Europe/Berlin"
    ports:
    - "80:8080"
    - "443:8443"
    networks:
      netology-lesson:
        ipv4_address: 172.19.0.5
    restart: always

networks:
  netology-lesson:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24
