---

 - name: "change motd from env"
   hosts: debian
   become: yes
   become_method: sudo
   vars:
    myline: "HELLO MASTER"
   tags: motd
   tasks:
      - name: "remove string in motd"
        ansible.builtin.lineinfile:
          path: /etc/motd
          regexp: '.*'
          state: absent
      - name: "modify permissions def file"
        tags: perm
        ansible.builtin.file:
          path: /etc/update-motd.d
          state: directory
          recurse: true
          mode: '0500'
      - name: "modify motd"
        ansible.builtin.template:
          source: tempaltes/motd.j2
          dest: /etc/motd
