version: "3"
include:
  - proxy.yaml
services:
  web:
    image: cr.yandex/crp1oktedotpk7qgibjh/myapp:l.0
    ports:
      - "5000:5000"
    networks:
      backend:
        ipv4_address: 172.20.0.5
    restart: on-failure
    env_file:
      - .envPy
    depends_on:
      - db
  
  db:
    image: mysql:8
    restart: on-failure
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      backend:
        ipv4_address: 172.20.0.10
  
volumes:
  db_data: {}
    
        
