apiVersion: v1
kind: Namespace
metadata:
  name: netology
  labels:
    name: netology
    
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: netology
  name: podinfo-viewer
rules:
- apiGroups: [""]
  resources: ["pods","pods/log"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: netology
subjects:
- kind: User
  name: myuser
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: podinfo-viewer
  apiGroup: rbac.authorization.k8s.io