apiVersion: v1
kind: ServiceAccount
metadata:
  name: app1serviceaccount

---
apiVersion: v1
kind: Secret
metadata:
  name: extra-default-secret
  annotations:
    kubernetes.io/service-account.name: app1serviceaccount
type: kubernetes.io/service-account-token