{
 "title": "NODE",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   { "name": "Instance", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "LA !",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "LA 5",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load5", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "LA 15",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load15", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Freee mem",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemFree_bytes{instance=\"$Instance\"} / node_memory_MemTotal_bytes{instance=\"$Instance\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IDLE % CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": " round(100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[5m])) * 100))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "free spice hdd",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes{instance=\"$Instance\"} * 100) / node_filesystem_size_bytes{instance=\"$Instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}