---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apps.name }}
  namespace: {{ .Values.apps.namespace }}
spec:
  replicas: {{ .Values.apps.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.apps.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.apps.name }}
    spec:
      containers:
        - name: {{ .Values.apps.name }}
          image: {{ .Values.apps.image.repository }}:{{ .Values.apps.image.tag }}
          ports:
            - containerPort: {{ .Values.apps.containerPort }}