apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apps.name }}-service
  namespace: {{ .Values.apps.namespace }}
spec:
  selector:
    app: {{ .Values.apps.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.apps.containerPort }}
  type: ClusterIP
