#version: '3.9'
name: homework 

services: 

   postgresql:
    image: postgres:15-bookworm
    environment:
      POSTGRES_PASSWORD: 1234567
    volumes:
      - pgdata:/var/lib/postgresql/data
      - backups:/backup
    networks:
      - bd

volumes:
  pgdata:
  backups:

networks:
  bd:
    name: homework


  


